apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
spec:
  goTemplate: true
  goTemplateOptions:
  - "missingkey=error"
  generators:
  - git:
      repoURL: https://github.com/luizscofield/descomplicando-gitops-no-kubernetes-argocd
      revision: day-3
      directories:
      - path: applicationset/apps/*/helm
  template:
    metadata:
      name: '{{index .path.segments 2}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/luizscofield/descomplicando-gitops-no-kubernetes-argocd
        targetRevision: day-3
        path: '{{.path.path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{index .path.segments 2}}'